---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(fitdist)
```


```{r}
x <- runif(100, 0, 1)
plot(dbeta(x, 50, 80) ~ x)
plot(dbeta(x, 2, 50) ~ x)
plot(dbeta(x, 500, 600) ~ x)
```

###Feuille 1 - Exercice 3

Question 3 :

```{r}
x <- runif(100, 0, 1)
curve(dgamma(x, 1, 0.5), xlim = c(0,3), ylim = c(0,4))
curve(dgamma(x, 1, 2), add = TRUE, col = 2)
curve(dgamma(x, 1, 10), add = TRUE, col = 3)
curve(dgamma(x, 2, 4), add = TRUE, col = 4)
```

Question 4 : 

```{r}
lambda <- 0.5

y20 <- rpois(20, lambda)
y100 <- rpois(100, lambda)
y1000 <- rpois(1000, lambda)
y10000 <- rpois(10000, lambda)


curve(dgamma(x, 1+sum(y20), 0.5 + 20), xlim= c(0, 3), ylim = c(0, 4))
curve(dgamma(x, 1+sum(y20), 2 + 20), add = TRUE, col = 2)
curve(dgamma(x, 1+sum(y20), 10 + 20), add = TRUE, col = 3)
curve(dgamma(x, 2+sum(y20), 2 + 20), add = TRUE, col = 4)
```


Question 5 :




### Feuille 2 - Exercice 1 



```{r}
deputes <- read.csv2("deputes.csv")
attach(deputes)
```

```{r}
glimpse(deputes)
```

Question 1

```{r}

lambdahat <- mean(deputes$questions_orales)
varhat <- var(questions_orales)

ggplot(deputes, aes(x = questions_orales, fill = sexe)) +
  geom_bar(prob = TRUE) +
  geom_point(aes(x = 0:8, y = dpois(0:8, lambdahat)))
```

La variance et la moyenne sont proches + la distribution, nous laissent penser qu'on peut utiliser une loi de Poisson.



Question 2 


```{r}

```



Question 4

cf code R de robin !!
```{r}

K = 1000
delta <- rep(NA, K)

for(i in 1:K){
  lambda1 <- rgamma(1, 2, 2)
  lambda2 <- rgamma(1, 2, 2)
  delta[i] <- lambda1 - lambda2 
}
mean(delta)
```





---------------------------


# 15 novembre 2018

Estimer E[cos(x)] où X ~ Exp(10)

```{r}
lambda = 10
n <- 1e7
x <- rexp(n, lambda)
mean(cos(x))
```


Vérifions la convergence

```{r}
plot(cumsum(cos(x))/(1:n), type="l")
```

Valeur exacte par intégration numérique

```{r}
integrate(function(x){cos(x) * lambda * exp(-lambda * x)}, 0, Inf)
```

Estimons P[x>1]

```{r}
mean(x>1)
pexp(1, 10, lower=F) # valeur théorique
```




```{r}
y <- rexp(n, 1)
mean((y>1) * dexp(y, 10)/dexp(y, 1))
plot(cumsum(((y>1) * dexp(y, 10)/dexp(y, 1)))/(1:n), type = "l")
```


```{r}
curve(dexp(x, 10), xlim=c(0, 5))
curve(dexp(x, 1), add=T, col=2)
```





